
package com.widgetpublica.wsdl.client.ECMDocumentService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://ws.dm.ecm.technology.totvs.com/")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.widgetpublica.wsdl.client.ECMDocumentService.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Exception_Exception(String message, com.widgetpublica.wsdl.client.ECMDocumentService.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Exception_Exception(String message, com.widgetpublica.wsdl.client.ECMDocumentService.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.widgetpublica.wsdl.client.ECMDocumentService.Exception
     */
    public com.widgetpublica.wsdl.client.ECMDocumentService.Exception getFaultInfo() {
        return faultInfo;
    }

}
